CREATE DATABASE dbtiendademascota
go
USE dbtiendademascota
GO


-- tables
-- Table: CLIENTE
CREATE TABLE CLIENTE (
    NOMCLI varchar(50)  NOT NULL,
    APELCLI varchar(50)  NOT NULL,
    GMACLI char(50)  NOT NULL,
    TELCLI char(9)  NOT NULL,
    DIRCLI char(50)  NOT NULL,
    CODCLI char(6)  NOT NULL,
    DNICLI char(8)  NOT NULL,
    CONSTRAINT CLIENTE_pk PRIMARY KEY (CODCLI)
);
GO

-- Table: PRODUCTO
CREATE TABLE PRODUCTO (
    NOMPRO varchar(50)  NOT NULL,
    CODPRO char(6)  NOT NULL,
    PREPRO decimal(14,5)  NOT NULL,
    STROPRO int  NOT NULL,
    ESTAPRO char(6)  NOT NULL,
    VENTA_IDVENT char(6)  NOT NULL,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY (CODPRO)
);
GO
-- Table: VENDEDOR
CREATE TABLE VENDEDOR (
    NOMVEND varchar(50)  NOT NULL,
    APELVEND varchar(50)  NOT NULL,
    GMAVEND char(50)  NOT NULL,
    TELVEND char(9)  NOT NULL,
    DIRVEND char(50)  NOT NULL,
    CODVEND char(6)  NOT NULL,
    DNIVEND char(8)  NOT NULL,
    CLIENTE_CODCLI char(6)  NOT NULL,
    CONSTRAINT VENDEDOR_pk PRIMARY KEY (CODVEND)
);
GO
-- Table: VENTA
CREATE TABLE VENTA (
    IDVENT char(6)  NOT NULL,
    CODVEND char(6)  NOT NULL,
    CODCLI char(6)  NOT NULL,
    VENDEDOR_CODVEND char(6)  NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (IDVENT)
);
GO
-- Table: VENTA DE DETALLE
CREATE TABLE VENTA DE DETALLE (
    IDVENTDET int  NOT NULL,
    CODPRO int  NOT NULL,
    IDVENT int  NOT NULL,
    PRODUCTO_CODPRO char(6)  NOT NULL
);

-- foreign keys
-- Reference: PRODUCTO_VENTA (table: PRODUCTO)
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_VENTA
    FOREIGN KEY (VENTA_IDVENT)
    REFERENCES VENTA (IDVENT)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: VENDEDOR_CLIENTE (table: VENDEDOR)
ALTER TABLE VENDEDOR ADD CONSTRAINT VENDEDOR_CLIENTE
    FOREIGN KEY (CLIENTE_CODCLI)
    REFERENCES CLIENTE (CODCLI)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: VENTA DE DETALLE_PRODUCTO (table: VENTA DE DETALLE)
ALTER TABLE VENTA DE DETALLE ADD CONSTRAINT VENTA DE DETALLE_PRODUCTO
    FOREIGN KEY (PRODUCTO_CODPRO)
    REFERENCES PRODUCTO (CODPRO)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: VENTA_VENDEDOR (table: VENTA)
ALTER TABLE VENTA ADD CONSTRAINT VENTA_VENDEDOR
    FOREIGN KEY (VENDEDOR_CODVEND)
    REFERENCES VENDEDOR (CODVEND)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- End of file.

